-- AlterTable
ALTER TABLE "NEVERAS" ADD COLUMN     "fecha_activacion" TIMESTAMP(3),
ADD COLUMN     "fecha_creacion" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "TIENDAS" ADD COLUMN     "fecha_creacion" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
