services:
  db:
    image: postgres:16
    container_name: vorak_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: mi_base_de_datos
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backup:
    build: ./backup
    container_name: vorak_backup
    restart: always
    depends_on:
      - db
    volumes:
      - ./backups:/backups
    environment:
      PGPASSWORD: password123
    networks:
      - app-network

volumes:
 postgres_data:

networks:
  app-network:
    driver: bridge