-- AlterTable
ALTER TABLE "TRANSACCIONES" ADD COLUMN "id_nevera" INTEGER;

-- AddForeignKey
ALTER TABLE "TRANSACCIONES" ADD CONSTRAINT "TRANSACCIONES_id_nevera_fkey" FOREIGN KEY ("id_nevera") REFERENCES "NEVERAS"("id_nevera") ON DELETE SET NULL ON UPDATE CASCADE;
