-- RenameTable
ALTER TABLE "public"."STOCK_NEVERA_PRODUCTO" RENAME TO "STOCK_NEVERA";

-- RenamePrimaryKey
ALTER TABLE "public"."STOCK_NEVERA" RENAME CONSTRAINT "STOCK_NEVERA_PRODUCTO_pkey" TO "STOCK_NEVERA_pkey";

-- DropForeignKey
ALTER TABLE "public"."STOCK_NEVERA" DROP CONSTRAINT "STOCK_NEVERA_PRODUCTO_id_nevera_fkey";

-- DropForeignKey
ALTER TABLE "public"."STOCK_NEVERA" DROP CONSTRAINT "STOCK_NEVERA_PRODUCTO_id_producto_fkey";

-- AddForeignKey
ALTER TABLE "STOCK_NEVERA" ADD CONSTRAINT "STOCK_NEVERA_id_nevera_fkey" FOREIGN KEY ("id_nevera") REFERENCES "NEVERAS"("id_nevera") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "STOCK_NEVERA" ADD CONSTRAINT "STOCK_NEVERA_id_producto_fkey" FOREIGN KEY ("id_producto") REFERENCES "PRODUCTOS"("id_producto") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddColumn
ALTER TABLE "STOCK_NEVERA" ADD COLUMN "hora_calificacion" TIMESTAMP(3);
