-- AlterTable
ALTER TABLE "PRODUCTOS" ADD COLUMN     "alta" DOUBLE PRECISION,
ADD COLUMN     "baja" DOUBLE PRECISION,
ADD COLUMN     "media" DOUBLE PRECISION;

-- DropForeignKey
ALTER TABLE "EMPAQUES" DROP CONSTRAINT "EMPAQUES_id_estacion_fkey";

-- AlterTable
ALTER TABLE "ESTACIONES" DROP CONSTRAINT "ESTACIONES_pkey",
ADD COLUMN     "activa" BOOLEAN NOT NULL DEFAULT false,
ALTER COLUMN "id_estacion" DROP DEFAULT,
ALTER COLUMN "id_estacion" TYPE TEXT,
ADD CONSTRAINT "ESTACIONES_pkey" PRIMARY KEY ("id_estacion");

-- AlterTable
ALTER TABLE "EMPAQUES" ALTER COLUMN "id_estacion" TYPE TEXT;

-- AddForeignKey
ALTER TABLE "EMPAQUES" ADD CONSTRAINT "EMPAQUES_id_estacion_fkey" FOREIGN KEY ("id_estacion") REFERENCES "ESTACIONES"("id_estacion") ON DELETE RESTRICT ON UPDATE CASCADE;
