-- AlterTable
ALTER TABLE "BIBLIOTECA" ADD COLUMN     "id_admin" INTEGER;

-- AlterTable
ALTER TABLE "CIUDAD" ADD COLUMN     "id_admin" INTEGER;

-- AlterTable
ALTER TABLE "DEPARTAMENTO" ADD COLUMN     "id_admin" INTEGER;

-- AlterTable
ALTER TABLE "EMPAQUES" ADD COLUMN     "id_admin" INTEGER;

-- AlterTable
ALTER TABLE "ESTACIONES" ADD COLUMN     "id_admin" INTEGER;

-- AlterTable
ALTER TABLE "FRIGORIFICO" ADD COLUMN     "id_admin" INTEGER;

-- AlterTable
ALTER TABLE "ITEMS_DE_REPRODUCCION" ADD COLUMN     "id_admin" INTEGER;

-- AlterTable
ALTER TABLE "LISTA_DE_REPRODUCCION" ADD COLUMN     "id_admin" INTEGER;

-- AlterTable
ALTER TABLE "LOGISTICA" ADD COLUMN     "id_admin" INTEGER;

-- AlterTable
ALTER TABLE "NEVERAS" ADD COLUMN     "id_admin" INTEGER;

-- AlterTable
ALTER TABLE "PRODUCTOS" ADD COLUMN     "id_admin" INTEGER;

-- AlterTable
ALTER TABLE "PROMOCIONES" ADD COLUMN     "id_admin" INTEGER;

-- AlterTable
ALTER TABLE "REPORTE_ESTADO_NEVERAS" ADD COLUMN     "id_admin" INTEGER;

-- AlterTable
ALTER TABLE "STOCK_NEVERA" ADD COLUMN     "id_admin" INTEGER;

-- AlterTable
ALTER TABLE "TIENDAS" ADD COLUMN     "id_admin" INTEGER;

-- AlterTable
ALTER TABLE "TRANSACCIONES" ADD COLUMN     "id_admin" INTEGER;

-- AlterTable
ALTER TABLE "USUARIOS" ADD COLUMN     "id_admin" INTEGER;

-- AddForeignKey
ALTER TABLE "USUARIOS" ADD CONSTRAINT "USUARIOS_id_admin_fkey" FOREIGN KEY ("id_admin") REFERENCES "USUARIOS"("id_usuario") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DEPARTAMENTO" ADD CONSTRAINT "DEPARTAMENTO_id_admin_fkey" FOREIGN KEY ("id_admin") REFERENCES "USUARIOS"("id_usuario") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CIUDAD" ADD CONSTRAINT "CIUDAD_id_admin_fkey" FOREIGN KEY ("id_admin") REFERENCES "USUARIOS"("id_usuario") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TIENDAS" ADD CONSTRAINT "TIENDAS_id_admin_fkey" FOREIGN KEY ("id_admin") REFERENCES "USUARIOS"("id_usuario") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FRIGORIFICO" ADD CONSTRAINT "FRIGORIFICO_id_admin_fkey" FOREIGN KEY ("id_admin") REFERENCES "USUARIOS"("id_usuario") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LOGISTICA" ADD CONSTRAINT "LOGISTICA_id_admin_fkey" FOREIGN KEY ("id_admin") REFERENCES "USUARIOS"("id_usuario") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "NEVERAS" ADD CONSTRAINT "NEVERAS_id_admin_fkey" FOREIGN KEY ("id_admin") REFERENCES "USUARIOS"("id_usuario") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PRODUCTOS" ADD CONSTRAINT "PRODUCTOS_id_admin_fkey" FOREIGN KEY ("id_admin") REFERENCES "USUARIOS"("id_usuario") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PROMOCIONES" ADD CONSTRAINT "PROMOCIONES_id_admin_fkey" FOREIGN KEY ("id_admin") REFERENCES "USUARIOS"("id_usuario") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EMPAQUES" ADD CONSTRAINT "EMPAQUES_id_admin_fkey" FOREIGN KEY ("id_admin") REFERENCES "USUARIOS"("id_usuario") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "REPORTE_ESTADO_NEVERAS" ADD CONSTRAINT "REPORTE_ESTADO_NEVERAS_id_admin_fkey" FOREIGN KEY ("id_admin") REFERENCES "USUARIOS"("id_usuario") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TRANSACCIONES" ADD CONSTRAINT "TRANSACCIONES_id_admin_fkey" FOREIGN KEY ("id_admin") REFERENCES "USUARIOS"("id_usuario") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "STOCK_NEVERA" ADD CONSTRAINT "STOCK_NEVERA_id_admin_fkey" FOREIGN KEY ("id_admin") REFERENCES "USUARIOS"("id_usuario") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BIBLIOTECA" ADD CONSTRAINT "BIBLIOTECA_id_admin_fkey" FOREIGN KEY ("id_admin") REFERENCES "USUARIOS"("id_usuario") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LISTA_DE_REPRODUCCION" ADD CONSTRAINT "LISTA_DE_REPRODUCCION_id_admin_fkey" FOREIGN KEY ("id_admin") REFERENCES "USUARIOS"("id_usuario") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ITEMS_DE_REPRODUCCION" ADD CONSTRAINT "ITEMS_DE_REPRODUCCION_id_admin_fkey" FOREIGN KEY ("id_admin") REFERENCES "USUARIOS"("id_usuario") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ESTACIONES" ADD CONSTRAINT "ESTACIONES_id_admin_fkey" FOREIGN KEY ("id_admin") REFERENCES "USUARIOS"("id_usuario") ON DELETE SET NULL ON UPDATE CASCADE;
